// Code generated by "stringer -type=InvalidParameterCombinationRenderPolicy"; DO NOT EDIT.

package optimization

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Omit-1]
	_ = x[AssignClosestValidValue-2]
}

const _InvalidParameterCombinationRenderPolicy_name = "OmitAssignClosestValidValue"

var _InvalidParameterCombinationRenderPolicy_index = [...]uint8{0, 4, 27}

func (i InvalidParameterCombinationRenderPolicy) String() string {
	i -= 1
	if i < 0 || i >= InvalidParameterCombinationRenderPolicy(len(_InvalidParameterCombinationRenderPolicy_index)-1) {
		return "InvalidParameterCombinationRenderPolicy(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _InvalidParameterCombinationRenderPolicy_name[_InvalidParameterCombinationRenderPolicy_index[i]:_InvalidParameterCombinationRenderPolicy_index[i+1]]
}
